version: '3.8'

services:
  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: secureguard-jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
      - "4318:4318"    # OTLP HTTP receiver
      - "14268:14268"  # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - secureguard-telemetry

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: secureguard-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - secureguard-telemetry

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: secureguard-grafana
    ports:
      - "3001:3000"  # Using 3001 to avoid conflict with frontend
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secureguard
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - jaeger
    networks:
      - secureguard-telemetry

  # OpenTelemetry Collector (optional, for advanced routing)
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: secureguard-otel-collector
    ports:
      - "4319:4317"   # OTLP gRPC receiver (alternative port)
      - "4320:4318"   # OTLP HTTP receiver (alternative port)
      - "8888:8888"   # Prometheus metrics
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check
      - "55679:55679" # ZPages
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]
    depends_on:
      - jaeger
      - prometheus
    networks:
      - secureguard-telemetry

networks:
  secureguard-telemetry:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data: