global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape SecureGuard API metrics
  - job_name: 'secureguard-api'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          service: 'secureguard-api'
          environment: 'development'
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Scrape Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
        labels:
          service: 'jaeger'

  # Scrape OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
        labels:
          service: 'otel-collector'

  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

# Alert rules (optional)
rule_files:
  # - 'alerts.yml'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093